version: '3'
services:
  web:
    build: .
    container_name: flask-wa
    ports:
      - "5000:5000"
    volumes:
      - .:/src
    links:
      - db
  db:
    image: mongo:3.6.0
    ports:
      - "27017:27017"